import type { Metadata } from 'next';
import { Readex_Pro } from 'next/font/google';
import './globals.css';

const readex = Readex_Pro({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${readex.className} antialiased`}>{children}</body>
    </html>
  );
}
